# Generated by Django 4.2.5 on 2023-09-08 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("endpoint", "0002_deliveryrecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryrecord",
            old_name="subscriber",
            new_name="email",
        ),
    ]
