# Generated by Django 4.2.5 on 2023-09-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoint", "0004_alter_deliveryrecord_time_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrecord",
            name="time_sent",
            field=models.DateTimeField(),
        ),
    ]
